module.exports.ASTRSCArrays = [
    "pan-african",
    "pan african",
    "african studies",
    "african union",
    "south africa",
    "west africa",
    "north africa",
    "east africa",
    "southern africa",
    "northern africa",
    "eastern africa",
    "western africa",
    "african american",
    "central african republic",
    "central africa",
    "african national congress",
    "africanize",
    "african development bank group",
    "great star of africa",
    "world resources institute africa",
    "power shift africa",
    "scramble for africa",
    "black african",
    "african-american",
    "french equitorial africa", 
    "gbv",
    "gender-based violence",
    "gender based violence",
    "violenc",
    "conflict",
    "war",
    "wars",
    "warring",
    "warfare",
    "warship",
    "wartime",
    "warzone",
    "warzones",
    "civil war",
    "atroc",
    "crime",
    "violent",
    "weapon",
    "insurg",
    "chao",
    "arm",
    "terror",
    "flee",
    "militia",
    "outbreak",
    "crisis",
    "crises",
    "brutal",
    "collaps",
    "tension",
    "rebel",
    "genocid",
    "clash",
    "dead",
    "erupt",
    "crimin",
    "abus",
    "escal",
    "rape",
    "sanction",
    "corrupt",
    "radic",
    "ban",
    "bans",
    "banned",
    "banning",
    "bomb",
    "blood",
    "cease-fir",
    "coup",
    "coups",
    "assault",
    "kidnap",
    "battl",
    "abduct",
    "aggressor",
    "ambush",
    "anarch",
    "assassin",
    "attack",
    "authoritarian",
    "brigad",
    "carnag",
    "casualt",
    "counterterror",
    "decimat",
    "destabil",
    "destroy",
    "destruct",
    "dictator",
    "die",
    "death",
    "disast",
    "emergency",
    "emergencies",
    "enemy",
    "enemies",
    "exil",
    "explod",
    "explos",
    "extremis",
    "famin",
    "fascist",
    "fatal",
    "foment",
    "fighter",
    "gang",
    "grenad",
    "grim",
    "gun",
    "harass",
    "harrow",
    "horrif",
    "horror",
    "hostag",
    "hostil",
    "imprison",
    "instab",
    "jail",
    "kill",
    "loot",
    "lynch",
    "massacr",
    "milit",
    "missil",
    "murder",
    "overthr",
    "paramilitar",
    "paratroop",
    "persecut",
    "pillag",
    "prison",
    "raid",
    "ravag",
    "retali",
    "riot",
    "shoot",
    "slaughter",
    "smuggl",
    "smuggled weapons",
    "child soldier",
    "soldier",
    "suffer",
    "terrorist",
    "traffick",
    "tortur",
    "troop",
    "unrest",
    "fled",
    "ransom",
    "bandit",
    "air strike",
    "airstrike",
    "arrest",
    "intimidation",
    "accus",
    "victim",
    "inmate",
    "pain",
    "tyranny",
    "bribe",
    "extort",
    "cartel",
    "battlefield",
    "repress",
    "suppress",
    "dying",
    "malnourish",
    "starv",
    "displace",
    "topple",
    "harm",
    "artillery",
    "coup d'etat",
    "mass execut",
    "execut",
    "guerilla",
    "detention camp",
    "jungle",
    "big game",
    "wildlif",
    "fauna",
    "habitat",
    "conservatio",
    "animal",
    "livestock",
    "safari park",
    "park",
    "parks",
    "biota",
    "egyptian gees",
    "egyptian goos",
    "nature",
    "camping",
    "wildcat",
    "savag",
    "wild-typ",
    "waterfowl",
    "barbary stag",
    "ecolog",
    "biodivers",
    "wildfowl",
    "endangered speci",
    "raptor",
    "wetland",
    "spotted necked ott",
    "african clawless ott",
    "congo clawless ott",
    "eurasian ott",
    "fisheri",
    "waterbird",
    "poacher",
    "bird sanctuar",
    "ecosystem",
    "reptil",
    "naturalist",
    "waterway",
    "wildflow",
    "ecotour",
    "seabird",
    "african spurred tortois",
    "amphibian",
    "wolves",
    "stone curlew",
    "african sacred ibi",
    "sacred ibi",
    "african monarch butterfl",
    "monarch butterfl",
    "plain tig",
    "african monarch",
    "african goshawk",
    "goshawk",
    "cirl bunt",
    "seafowl",
    "bird of passag",
    "shore bird",
    "african black oystercatch",
    "water thick-kne",
    "white-fronted plov",
    "blacksmith plov",
    "common sandpip",
    "zoo",
    "mammal",
    "gallery forest",
    "bird tabl",
    "sea cow",
    "manate",
    "tropical rain forest",
    "sea eleph",
    "elephant seal",
    "sea leopard",
    "aquatic bird",
    "african wild dog",
    "marine anim",
    "african eleph",
    "miombo woodland",
    "woodland",
    "elephant bird",
    "rangership",
    "wildgrav",
    "exotic",
    "aquat",
    "vertebr",
    "mammalian",
    "scenic",
    "endemic",
    "ocean",
    "underwat",
    "predator",
    "plant",
    "plants",
    "soil",
    "wildland",
    "extinct",
    "poach",
    "watersh",
    "waterfal",
    "invertebr",
    "extermin",
    "shellfish",
    "african buffalo",
    "songbird",
    "forest rang",
    "game warden",
    "gamekeep",
    "preservationist",
    "safari",
    "biospher",
    "environment",
    "freshwat",
    "herbivor",
    "pygmy hippopotamus",
    "ladybug",
    "golden eagl",
    "oranda goldfish",
    "cheetah",
    "rabbit",
    "scorpion",
    "critically endang",
    "comet moth",
    "bongo",
    "white rhinoceros",
    "madagascar cockroach",
    "dolphin",
    "eastern green mamba",
    "night heron",
    "twig snak",
    "ostrich",
    "flycatch",
    "vervet monkey",
    "northern white rhinocero",
    "angelshark",
    "olive baboon",
    "green bee eat",
    "flamingo",
    "shrimp",
    "fiddler crab",
    "dove",
    "jumping spid",
    "carpet vip",
    "horsefl",
    "jackson's chameleon",
    "donkey",
    "mosquito",
    "sparrow",
    "macaqu",
    "short-eared owl",
    "dragonfl",
    "chimp",
    "birds of prey",
    "suni",
    "cape buffalo",
    "striped hyena",
    "mountain gorilla",
    "madagascar hissing cockroach",
    "african civet",
    "cuckoo",
    "nile crocodil",
    "horned add",
    "butterfl",
    "cape elephant shrew",
    "guinea fowl",
    "brown hyena",
    "yellow cobra",
    "pig",
    "warbler",
    "woodpeck",
    "wild boar",
    "chimpanze",
    "snake",
    "hammerhead",
    "liger",
    "extirp",
    "bumblebe",
    "jellyfish",
    "southeastern black rhino",
    "peacock",
    "radiated tortois",
    "eurasian jay",
    "sardin",
    "wild cat",
    "cod",
    "springbok",
    "jackal",
    "sea eagl",
    "cross river gorilla",
    "hoopo",
    "water buffalo",
    "common furniture beetl",
    "black rhino",
    "zebu",
    "scimitar-horned oryx",
    "kingfish",
    "african tree toad",
    "impala",
    "gerbil",
    "vinegaroon",
    "biscuit beetl",
    "devil's coach horse beetl",
    "lesser kudu",
    "gnat",
    "bird snak",
    "ring-tailed lemur",
    "huntsman spid",
    "bichir",
    "common wildebeest",
    "egyptian cobra",
    "egyptian asp",
    "linnet",
    "griffon vultur",
    "porcupin",
    "forest cobra",
    "egyptian tortois",
    "spider ball python",
    "forest hog",
    "african penguin",
    "dusky shark",
    "barb",
    "barbs",
    "mole snak",
    "madagascar jacana",
    "termit",
    "chicken",
    "moorhen",
    "african grey parrot",
    "graylag goos",
    "red deer",
    "wryneck",
    "lionfish",
    "golden oriol",
    "stick insect",
    "aardvark",
    "european polecat",
    "african bush eleph",
    "red kit",
    "grey mouse lemur",
    "false widow spid",
    "lechwe antelop",
    "crested cran",
    "blue whal",
    "puku",
    "bald eagl",
    "orb weav",
    "vine snak",
    "skink lizard",
    "king cobra",
    "sheep",
    "pheasant",
    "horned vip",
    "bat-eared fox",
    "silky shark",
    "dik-dik",
    "fossa",
    "tiger beetl",
    "manta ray",
    "xerus",
    "camel",
    "quail",
    "okapi",
    "senegal parrot",
    "marabou stork",
    "achrioptera manga",
    "brown bear",
    "desert rain frog",
    "river turtl",
    "african palm civet",
    "african gray parrot",
    "stiletto snak",
    "carac",
    "honey badg",
    "rhino",
    "nigerian goat",
    "rock hyrax",
    "peregrine falcon",
    "crane",
    "crow",
    "crows",
    "song thrush",
    "fire ball python",
    "dinopithecus",
    "electric catfish",
    "lappet-face vultur",
    "banana spid",
    "bush babi",
    "marlin",
    "hamadryas baboon",
    "nyala",
    "bushbabi",
    "galago",
    "woodlouse spid",
    "spotted hyena",
    "kestrel",
    "satanic leaf-tailed gecko",
    "goldcrest",
    "scimitar oryx",
    "desert warthog",
    "barracuda",
    "grasshopp",
    "coton de tulear",
    "egyptian mau",
    "red spitting cobra",
    "hedgehog",
    "duiker",
    "bonobo",
    "housefl",
    "sand vip",
    "mozambique spitting cobra",
    "common hippo",
    "goliath beetl",
    "porpois",
    "oribi",
    "hamster",
    "black rhinocero",
    "bearded vultur",
    "green bee-eat",
    "fennec fox",
    "gembsok oryx",
    "woodlous",
    "waterbuck",
    "dumeril's boa",
    "indri",
    "brown dog tick",
    "black rhinoceros",
    "common carp",
    "galapagos shark",
    "grant's gazell",
    "axanthic ball python",
    "african lion",
    "grey heron",
    "rooster",
    "parakeet",
    "african golden cat",
    "lappet-faced vultur",
    "strawberry hermit crab",
    "redstart",
    "black widow spid",
    "wildebeest",
    "gnu",
    "lichtenstein's hartebeest",
    "fruit bat",
    "orange baboon tarantula",
    "patas monkey",
    "weasel",
    "uromastyx",
    "sea turtl",
    "agama lizard",
    "turaco",
    "egyptian vultur",
    "giant african land snail",
    "saturniidae moth",
    "sunset ball python",
    "addra gazell",
    "thomson's gazell",
    "blind snak",
    "lavender albino ball python",
    "abyssinian",
    "goliath tigerfish",
    "eastern lowland gorilla",
    "sable bul",
    "sable antelop",
    "european goldfinch",
    "cichlid",
    "whinchat",
    "banana cinnamon ball python",
    "bush eleph",
    "mouse",
    "mice",
    "western lowland gorilla",
    "eland",
    "giant ground pangolin",
    "brown-banded cockroach",
    "zonkey",
    "sei whal",
    "slug",
    "african jacana",
    "african bullfrog",
    "dugong",
    "sand cat",
    "hawk moth caterpillar",
    "yellowfin tuna",
    "roan",
    "ibex",
    "madagascar tree boa",
    "african forest eleph",
    "orange dream ball python",
    "viper",
    "ethiopian wolf",
    "yellow mongoos",
    "bontebok",
    "aidi",
    "sperm whal",
    "kitefin shark",
    "tarantula hawk",
    "rodent",
    "white rhinocero",
    "praying manti",
    "meerkat",
    "black panth",
    "minke whal",
    "coryphodon",
    "honey bee",
    "cicada",
    "eel catfish",
    "white ferret",
    "albino ferret",
    "greater kudu",
    "africanized bee",
    "killer bee",
    "mallard",
    "gerenuk",
    "waller's gazell",
    "kori bustard",
    "dwarf crocodil",
    "fin whal",
    "pufferfish",
    "dormous",
    "spiny bush vip",
    "bush vip",
    "tsetse fl",
    "glow worm",
    "bale mountain vervet",
    "vanga",
    "european robin",
    "chameleon",
    "rock python",
    "anteat",
    "red fox",
    "peringuey's add",
    "bloodhound",
    "european bee-eat",
    "steinbok",
    "goliath frog",
    "fulvous whistling duck",
    "hornbil",
    "crab spid",
    "bed bug",
    "spider wasp",
    "snouted cobra",
    "humpback whal",
    "avocet",
    "flea",
    "myna bird",
    "african savannah eleph",
    "hare",
    "reedbuck",
    "the blue monkey",
    "shoebill stork",
    "caecilian",
    "pike",
    "dung beetl",
    "codling moth",
    "beisa oryx",
    "brahminy blindsnak",
    "western gorilla",
    "cape bushbuck",
    "basenji dog",
    "ant",
    "ants",
    "kudus",
    "mealybug",
    "deathwatch beetl",
    "yellow belly ball python",
    "sitatunga",
    "bale monkey",
    "aye-ay",
    "zebra spitting cobra",
    "sable ferret",
    "african fish eagl",
    "maggot",
    "no see um",
    "no-see-um",
    "leech",
    "eastern gorilla",
    "thrush",
    "klipspring",
    "german cockroach",
    "common hippopotamus",
    "colobus monkey",
    "fruit fl",
    "great dan",
    "nightingal",
    "magpi",
    "mantella frog",
    "sand crab",
    "american cockroach",
    "genet",
    "hognose snak",
    "willow warbl",
    "quelea quelea",
    "nguni cattl",
    "banana ball python",
    "falcon",
    "stingray",
    "earwig",
    "red-billed quelea bird",
    "lemur",
    "barn swallow",
    "african clawed frog",
    "zebra snak",
    "sulcata tortois",
    "centiped",
    "osprey",
    "giraff",
    "lungfish",
    "monitor lizard",
    "freeway ball python",
    "gaboon vip",
    "stallion",
    "robin",
    "puss moth",
    "wasp",
    "lesser jacana",
    "mule",
    "mandril",
    "zors",
    "peafowl",
    "false cobra",
    "barn owl",
    "smokybrown cockroach",
    "shoebil",
    "killer whale",
    "whalehead",
    "whale-headed stork",
    "whalebil",
    "salmon",
    "crab",
    "bushpig",
    "mole cricket",
    "wolf spid",
    "albacore tuna",
    "burchell's zebra",
    "albatross",
    "barbary boar",
    "boomslang",
    "seahors",
    "ortolan bunt",
    "gypsy moth",
    "topi",
    "topis",
    "desert locust",
    "killer clown ball python",
    "blue monkey",
    "pelican",
    "spitting cobra",
    "leopard tortois",
    "brazilian treehopp",
    "grey-crowned cran",
    "portuguese man-of-war",
    "freshwater eel",
    "mayfly",
    "mayflies",
    "blister beetl",
    "madora moth",
    "firefl",
    "common house spid",
    "dog tick",
    "beecroft's flying squirrel",
    "black mamba",
    "armyworm",
    "grevy's zebra",
    "common raven",
    "ibi",
    "tree frog",
    "aardwolf",
    "lobster",
    "cape hyrax",
    "locust",
    "serval",
    "rhino vip",
    "pigeon",
    "needlefish",
    "ground squirrel",
    "common buzzard",
    "cow",
    "cows",
    "reptilian",
    "earthworm",
    "jerboa",
    "addax",
    "white rhino",
    "kenyan sand boa",
    "brookesia micra",
    "spotted hyaena",
    "aye ay",
    "naked mole rat",
    "milliped",
    "caterpillar",
    "senepol cattl",
    "devils coach horse beetl",
    "puff add",
    "glass lizard",
    "west african wild dog",
    "western green mamba",
    "grysbok",
    "swan",
    "desert ghost ball python",
    "forest eleph",
    "wild dog",
    "wild",
    "otter",
    "bird",
    "turtl",
    "tortois",
    "rain forest",
    "forest",
    "leopard",
    "panther",
    "marin",
    "eagl",
    "seal",
    "green mamba",
    "mamba",
    "buffalo",
    "hyena",
    "crocodil",
    "elephant shrew",
    "gorilla",
    "oryx",
    "savannah eleph",
    "savannah",
    "tree",
    "horse",
    "beetl",
    "leaf-tailed gecko",
    "gecko",
    "hunt",
    "bee",
    "bees",
    "shark",
    "parrot",
    "goos",
    "gees",
    "deer",
    "insect",
    "lizard",
    "bat",
    "bats",
    "fox",
    "stork",
    "frog",
    "civet",
    "bush",
    "goat",
    "hyrax",
    "baboon",
    "hippo",
    "vultur",
    "gazell",
    "lion",
    "heron",
    "cattl",
    "cat",
    "cats",
    "black widow",
    "snail",
    "moth",
    "moths",
    "python",
    "pangolin",
    "cockroach",
    "jacana",
    "tuna",
    "boa",
    "boas",
    "eleph",
    "shrew",
    "wolf",
    "mongoos",
    "rhinoceros",
    "eel",
    "kudu",
    "worm",
    "mountain",
    "bee-eat",
    "duck",
    "cobra",
    "monkey",
    "bushbuck",
    "zebra",
    "fish",
    "owl",
    "tick",
    "squirrel",
    "mole",
    "cod",
    "cods",
    "antelop",
    "tiger",
    "catfish",
    "warthog",
    "whale",
    "cricket",
    "africa",
    "subsaharan",
    "continent",
    "sub-saharan", 
    "ethnic",
    "nomad",
    "bushmen",
    "tribe",
    "pygmy",
    "tribal",
    "clan",
  ];